#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
my_laptop_external_monitor=$(xrandr --query | grep 'VGA1')

if [[ $my_laptop_external_monitor = VGA1\ connected* ]]; then
	bspc monitor LVDS1 -d I II
	bspc monitor VGA1 -d III IV 
else
	bspc monitor LVDS1 -d I II  III IV 
fi

#colors
bspc config normal_border_color "#282a36"
bspc config active_border_color "#282a36"
bspc config focused_border_color "#d81b60"
bspc presel_feedback_color ""

# window configs
bspc config left_padding 10
bspc config right_padding 10
bspc config top_padding 34
bspc config bottom_padding 5
bspc config border_width         5
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a tilda state=floating
bspc config ignore_ewmh_focus true
#Lights up
xset led 3

#
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xrandr --output VGA1 --brightness 1.1 --gamma 1.1;
xrandr --output LVDS1 --brightness 0.9 	--gamma 0.9;

sleep 1 &

nitrogen --restore &
pulseaudio &
dunst &
flameshot &
/home/nopan/.config/polybar/launch.sh &
sleep 5 &

pkill picom ; picom -b &
notify-send "EVERYTHING IS FINE YOU CAN DO YOUR THING NOW." &
